# Generated by Django 4.2.15 on 2025-09-10 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('objective', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ValidationRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('severity', models.CharField(choices=[('info', 'info'), ('warn', 'warn'), ('block', 'block')], max_length=8)),
                ('logic_json', models.JSONField(default=dict)),
                ('failure_message', models.CharField(max_length=240)),
                ('version', models.CharField(default='1.0.0', max_length=24)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='policy.control')),
            ],
        ),
        migrations.CreateModel(
            name='StandardSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('reference_url', models.URLField(blank=True, default='')),
                ('version', models.CharField(default='1.0.0', max_length=24)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('jurisdiction', models.CharField(blank=True, default='', max_length=64)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy.standard')),
            ],
        ),
        migrations.CreateModel(
            name='RuleExecutionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.CharField(max_length=64)),
                ('context_id', models.CharField(max_length=64)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(max_length=16)),
                ('details', models.JSONField(default=dict)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.validationrule')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('industry', models.CharField(blank=True, default='', max_length=64)),
                ('rules', models.ManyToManyField(blank=True, to='policy.validationrule')),
            ],
        ),
        migrations.CreateModel(
            name='NonConformity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('open', 'open'), ('closed', 'closed')], default='open', max_length=16)),
                ('owner', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='policy.validationrule')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='document', max_length=32)),
                ('url', models.URLField(blank=True, default='')),
                ('file_hash', models.CharField(blank=True, default='', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='policy.control')),
            ],
        ),
        migrations.AddField(
            model_name='control',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='controls', to='policy.standardsection'),
        ),
    ]
