# Generated by Django 4.2.15 on 2025-09-10 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Ej: nif, nias, coso-erm, iso-31000', unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Marco normativo',
                'verbose_name_plural': 'Marcos normativos',
            },
        ),
        migrations.CreateModel(
            name='FrameworkSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Ej: seccion, norma, principio')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True)),
                ('framework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.framework')),
            ],
            options={
                'verbose_name': 'SecciÃ³n del marco',
                'verbose_name_plural': 'Secciones del marco',
                'unique_together': {('framework', 'code')},
            },
        ),
        migrations.CreateModel(
            name='KPIFrameworkLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('kpi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='framework_links', to='core.kpi')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_links', to='core.frameworksection')),
            ],
            options={
                'verbose_name': 'VinculaciÃ³n KPIâ€“Marco',
                'verbose_name_plural': 'Vinculaciones KPIâ€“Marco',
                'unique_together': {('kpi', 'section')},
            },
        ),
    ]
