# Generated by Django 4.2.15 on 2025-09-12 08:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_framework_frameworksection_kpiframeworklink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='framework',
            options={},
        ),
        migrations.AlterModelOptions(
            name='frameworksection',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kpiframeworklink',
            options={},
        ),
        migrations.RenameField(
            model_name='frameworksection',
            old_name='text',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='framework',
            name='url',
        ),
        migrations.RemoveField(
            model_name='kpiframeworklink',
            name='notes',
        ),
        migrations.AddField(
            model_name='kpiframeworklink',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kpiframeworklink',
            name='rationale',
            field=models.TextField(blank=True, help_text='Por qué este KPI se sustenta en esta sección'),
        ),
        migrations.AlterField(
            model_name='framework',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='frameworksection',
            name='code',
            field=models.CharField(help_text='Ej: IAS 1, IFRS 15, ISA 315, Principio 4', max_length=80),
        ),
    ]
